<?php

namespace App;

use Illuminate\Database\Eloquent\Model;

class Category extends Model
{
    protected $guarded =[];
    protected $hidden= ['deleted_at','created_at','updated_at'];

    public function products()
    {
        return $this->morphedByMany(Product::class,'categoriable');
    }

    public function parent_category()
    {
        return $this->belongsTo(Category::class,'parent_id');
    }
    public function child_categories()
    {
        return $this->hasMany(Category::class,'parent_id');
    }
    protected static function boot()
    {
        parent::boot(); // TODO: Change the autogenerated stub
//        static::addGlobalScope(new OrderByOrder());
    }
}
